### PR TITLE
Enhancements, adjustments, bug fixes and documentation for DFVL

### PR DESCRIPTION
**Pull request by larsbe**
Also addresses #74

### CODE REVIEW

**Comment by fkoehne** [comment]
Christian can you take a look and make a release version out of this please? Sascha and Lars are both on on a short vacation and I don't want to delay this.

**Comment by larsbe** [comment]
Currently the documentation of the Data Flow Validation Language is quite hidden, I'm happy to hear suggestions on how to integrate it to the front page.

**Comment by sdibernardo** [comment]
The documentation looks pretty good. But I have to agree that it might suffer attention from being just part of the list. What about making a small section in the main document and then reference the detailed documentation there?

**Comment by fkoehne** [comment]
:)

**Pull request merged**
